---
name: Pull request pre-check build & test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    name: Run the pre-commit hook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: pre-commit/action@v3.0.0

  build-container:
    name: Build and test the ipa-tuura container
    runs-on: ubuntu-latest
    if: github.repository_owner == 'freeipa'
    needs: [pre-commit]
    steps:
      - uses: actions/checkout@v3
      - name: build image
        id: build-image
        run: |
          sudo -E su
          podman build -t ipatuura -f Containerfile.test .
      - name: Deploy the service
        run: |
          sudo -E su
          podman run -d --privileged \
                 -p 8000:8000 -p 3501:3500 -p 4701:81 -p 4430:443 \
                 --hostname bridge.ipa.test \
                 --name bridge \
                 ipatuura
      - name: Run the unit tests
        run: |
          sudo -E su
          podman exec -it bridge sh -c "pip install coverage factory_boy &&
          coverage run manage.py test domains -v 2 &&
          coverage report &&
          coverage html"
